export const RUN_PYTHON_CODE_REQUEST = "RUN_PYTHON_CODE_REQUEST"
export const RUN_PYTHON_CODE_SUCCESS = "RUN_PYTHON_CODE_SUCCESS"
export const RUN_PYTHON_CODE_FAIL = "RUN_PYTHON_CODE_FAIL"
export const RUN_PYTHON_CODE_RESET = "RUN_PYTHON_CODE_RESET"