export const RUN_PYTHON_CODE_REQUEST = "RUN_PYTHON_CODE_REQUEST"
export const RUN_PYTHON_CODE_SUCCESS = "RUN_PYTHON_CODE_SUCCESS"
export const RUN_PYTHON_CODE_FAIL = "RUN_PYTHON_CODE_FAIL"
export const RUN_PYTHON_CODE_RESET = "RUN_PYTHON_CODE_RESET"

export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGIN_RESET = "LOGIN_RESET"

export const LOGOUT_REQUEST = "LOGOUT_REQUEST"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAIL = "LOGOUT_FAIL"
export const LOGOUT_RESET = "LOGOUT_RESET"

export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"
export const REGISTER_LOGIN = "REGISTER_LOGIN"
